# -*- coding: utf-8 -*-
"""automated_cellwise_feature_extraction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ve0wgUGLAUijcgCCbA818l1VOdGJsNuC

Revised to process a nested, per-condition Drive layout:

    Cellpose feature extractions/
    ├── imgs/<condition>/tiles/<name>.tif
    ├── masks/<condition>/<name>_masks.tif
    └── cellwise_metadata/<condition>/<name>_metadata.csv   (output)

Conditions are discovered automatically under imgs/ and processed one at a
time. The per-cell feature-extraction logic is unchanged.
"""

from google.colab import drive
drive.mount('/content/drive')

import os
from pathlib import Path
import tifffile
import numpy as np
import pandas as pd
from scipy import ndimage
from skimage.measure import regionprops_table
from tqdm.auto import tqdm

BASE_DIR = Path('/content/drive/My Drive/Fusion AI/Prof Huang Project/Cellpose feature extractions')
IMG_DIR  = BASE_DIR / 'imgs'
MASK_DIR = BASE_DIR / 'masks'
OUT_DIR  = BASE_DIR / 'cellwise_metadata'
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Feature-extraction params (same as the single-image notebook)
BAND_WIDTH = 2
RESTRICT_OUTWARD_TO_BG = True
IMG_EXTENSIONS = {'.tif', '.tiff'}

def process_image_mask_pair(image_path, mask_path, output_csv_path,
                            band_width=BAND_WIDTH,
                            restrict_outward_to_bg=RESTRICT_OUTWARD_TO_BG):
    """Run the existing feature-extraction pipeline on one (image, mask) pair
    and save the resulting per-cell dataframe as CSV. Returns the dataframe."""
    mask  = tifffile.imread(str(mask_path))
    image = tifffile.imread(str(image_path))

    if image.ndim == 2:
        image = image[..., None]

    cell_ids = np.unique(mask)
    cell_ids = cell_ids[cell_ids != 0]

    # Empty-mask short-circuit so we still write a (header-only) CSV
    if cell_ids.size == 0:
        df = pd.DataFrame(columns=[
            'area_px', 'elongation',
            'ch1_cellwise_mean_intensity',
            'ch2_cellwise_mean_membrane_intensity',
            'ch3_cellwise_mean_intensity',
        ])
        df.index.name = 'cell_id'
        df.to_csv(output_csv_path)
        return df

    # ----- Channels 1 & 3 (axis indices 0 and 2): whole-cell mean -----
    whole_cell_channels = [0, 2]
    whole_cell_means = {
        c: ndimage.mean(image[..., c], labels=mask, index=cell_ids)
        for c in whole_cell_channels
    }

    # ----- Channel 2 (axis index 1, VE-cadherin): membrane-band mean -----
    ve_cad = image[..., 1]
    slices = ndimage.find_objects(mask)
    membrane_means = np.full(len(cell_ids), np.nan)
    for i, cid in enumerate(cell_ids):
        sl = slices[cid - 1]
        if sl is None:
            continue
        padded = tuple(
            slice(max(s.start - band_width, 0),
                  min(s.stop  + band_width, mask.shape[d]))
            for d, s in enumerate(sl)
        )
        sub_mask = mask[padded]
        cell     = (sub_mask == cid)
        dilated  = ndimage.binary_dilation(cell, iterations=band_width)
        eroded   = ndimage.binary_erosion(cell, iterations=band_width)
        band     = dilated & ~eroded
        if restrict_outward_to_bg:
            band &= (sub_mask == cid) | (sub_mask == 0)
        px = ve_cad[padded][band]
        if px.size:
            membrane_means[i] = px.mean()

    # ----- Per-cell pixel area -----
    areas = np.bincount(mask.ravel())[cell_ids]

    # ----- Per-cell elongation (major / minor axis of the equivalent ellipse) -----
    props = pd.DataFrame(
        regionprops_table(mask, properties=('label', 'axis_major_length', 'axis_minor_length'))
    ).set_index('label')
    elongation = np.where(
        props['axis_minor_length'] > 0,
        props['axis_major_length'] / props['axis_minor_length'],
        np.nan,
    )
    elongation = pd.Series(elongation, index=props.index).reindex(cell_ids).to_numpy()

    # ----- Combine and save -----
    df = pd.DataFrame(
        {
            'area_px':                              areas,
            'elongation':                           elongation,
            'ch1_cellwise_mean_intensity':          whole_cell_means[0],
            'ch2_cellwise_mean_membrane_intensity': membrane_means,
            'ch3_cellwise_mean_intensity':          whole_cell_means[2],
        },
        index=cell_ids,
    )
    df.index.name = 'cell_id'
    df.to_csv(output_csv_path)
    return df


def discover_conditions(img_dir):
    """Return sorted condition names: every subfolder of imgs/ that has a tiles/ dir."""
    if not img_dir.exists():
        raise FileNotFoundError(f"imgs/ directory not found: {img_dir}")
    conditions = []
    for sub in sorted(img_dir.iterdir()):
        if sub.is_dir() and (sub / 'tiles').is_dir():
            conditions.append(sub.name)
        elif sub.is_dir():
            print(f"[warn] {sub.name} has no tiles/ subfolder — skipping")
    return conditions


def process_condition(condition):
    """Process every image/mask pair for one condition. Returns a stats dict."""
    tiles_dir = IMG_DIR / condition / 'tiles'
    mask_dir  = MASK_DIR / condition
    out_dir   = OUT_DIR / condition
    out_dir.mkdir(parents=True, exist_ok=True)

    if not mask_dir.exists():
        print(f"[warn] no masks/ folder for condition '{condition}' "
              f"(expected {mask_dir}) — all pairs will be skipped")

    image_files = sorted(
        p for p in tiles_dir.iterdir()
        if p.is_file() and p.suffix.lower() in IMG_EXTENSIONS
    )
    print(f"  Found {len(image_files)} image(s) in {tiles_dir}")

    processed = skipped = failed = 0
    for image_path in tqdm(image_files, desc=f"{condition} pairs", leave=False):
        mask_name = f"{image_path.stem}_masks{image_path.suffix}"
        mask_path = mask_dir / mask_name
        out_path  = out_dir / f"{image_path.stem}_metadata.csv"

        if not mask_path.exists():
            tqdm.write(f"  [skip] no mask for {image_path.name} (expected {mask_name})")
            skipped += 1
            continue

        try:
            process_image_mask_pair(image_path, mask_path, out_path)
            processed += 1
        except Exception as e:
            tqdm.write(f"  [fail] {image_path.name}: {e}")
            failed += 1

    return {
        'condition': condition,
        'total':     len(image_files),
        'processed': processed,
        'skipped':   skipped,
        'failed':    failed,
    }


# --------------------------------------------------------------------------- #
# Driver: process condition-by-condition, then print a grand summary
# --------------------------------------------------------------------------- #

conditions = discover_conditions(IMG_DIR)
print(f"Discovered {len(conditions)} condition(s): {conditions}\n")

all_stats = []
for i, condition in enumerate(conditions, start=1):
    print(f"========== [{i}/{len(conditions)}] {condition} ==========")
    stats = process_condition(condition)
    print(f"  -> processed={stats['processed']}  skipped={stats['skipped']}  "
          f"failed={stats['failed']}  (total={stats['total']})\n")
    all_stats.append(stats)

# ----- Grand summary across all conditions -----
g_processed = sum(s['processed'] for s in all_stats)
g_skipped   = sum(s['skipped']   for s in all_stats)
g_failed    = sum(s['failed']    for s in all_stats)
g_total     = sum(s['total']     for s in all_stats)

print("========== SUMMARY ==========")
print(f"{'condition':<22} {'processed':>9} {'skipped':>8} {'failed':>7} {'total':>7}")
for s in all_stats:
    print(f"{s['condition']:<22} {s['processed']:>9} {s['skipped']:>8} "
          f"{s['failed']:>7} {s['total']:>7}")
print('-' * 56)
print(f"{'ALL':<22} {g_processed:>9} {g_skipped:>8} {g_failed:>7} {g_total:>7}")
