# -*- coding: utf-8 -*-
"""ten_sample_disk_cached_dataloader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DtkH0VgTXji2raWuyyVdRsebo3tFhswX
"""

"""
FAST PARALLELIZED Disk-Cached Dataloader
Uses multi-threading to dramatically speed up Google Drive I/O

Expected precache time: 5-15 minutes (not hours!)
"""

# Mount Google Drive first!
from google.colab import drive
drive.mount("/content/drive")

import torch
from torch.utils.data import Dataset, DataLoader, ConcatDataset
from pathlib import Path
from PIL import Image
import numpy as np
from functools import lru_cache
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm

# ============================================================================
# PARALLEL LOADING UTILITIES
# ============================================================================

def load_single_zstack(well_id, tif_files, cache_path):
    """Load a single z-stack in parallel"""
    if cache_path.exists():
        return well_id, "cached"

    images = []
    for tif_path in tif_files:
        img = Image.open(tif_path)
        images.append(np.array(img))

    z_stack = np.stack(images, axis=0)
    np.save(cache_path, z_stack)

    return well_id, "loaded"


def load_single_focus(well_id, file_path, cache_path, target_size=(1440, 1920)):
    """Load a single focus image in parallel"""
    if cache_path.exists():
        return well_id, "cached"

    img_pil = Image.open(file_path)
    if target_size:
        img_pil = img_pil.resize((target_size[1], target_size[0]), Image.BILINEAR)

    img = np.array(img_pil)
    np.save(cache_path, img)

    return well_id, "loaded"


def load_single_hybrid(well_id, tif_path, cache_path):
    """Load a single hybrid image in parallel"""
    if cache_path.exists():
        return well_id, "cached"

    img = np.array(Image.open(tif_path))
    np.save(cache_path, img)

    return well_id, "loaded"

# ============================================================================
# PARALLELIZED DATASETS
# ============================================================================

class FastDiskCachedZStackDataset(Dataset):
    """Z-Stack dataset with parallel disk caching"""
    def __init__(self, root_dir, w_count, cache_dir="/content/cache/zstack"):
        self.root_dir = Path(root_dir)
        self.cache_dir = Path(cache_dir)
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        self.w_count = w_count

        # Scan directory structure
        self.samples = []
        for i in range(1, self.w_count + 1):
            w_id = f"W{i:03d}"
            p_folder = self.root_dir / w_id / "P00001"

            if not p_folder.exists():
                continue

            tif_files = sorted([
                p for p in p_folder.iterdir()
                if p.is_file() and p.suffix.lower() == ".tif"
            ])

            if len(tif_files) > 0:
                self.samples.append((w_id, tif_files))

        print(f"  Found {len(self.samples)} z-stack samples")

    def parallel_precache(self, max_workers=8):
        """Precache all data in parallel"""
        print(f"  Precaching {len(self.samples)} z-stacks with {max_workers} workers...")

        tasks = []
        for well_id, tif_files in self.samples:
            cache_path = self.cache_dir / f"{well_id}.npy"
            tasks.append((well_id, tif_files, cache_path))

        cached_count = 0
        loaded_count = 0

        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            futures = {
                executor.submit(load_single_zstack, w_id, tifs, cp): w_id
                for w_id, tifs, cp in tasks
            }

            with tqdm(total=len(tasks), desc="  Z-stacks") as pbar:
                for future in as_completed(futures):
                    well_id, status = future.result()
                    if status == "cached":
                        cached_count += 1
                    else:
                        loaded_count += 1
                    pbar.update(1)

        print(f"  ✓ Complete: {cached_count} already cached, {loaded_count} newly loaded")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        well_id, _ = self.samples[idx]
        cache_path = self.cache_dir / f"{well_id}.npy"

        if not cache_path.exists():
            raise RuntimeError(f"Cache missing for {well_id}. Run parallel_precache() first!")

        z_stack = np.load(cache_path)
        return (z_stack, well_id)

class FastDiskCachedFocusStackDataset(Dataset):
    """Focus-stacked dataset with parallel disk caching"""
    def __init__(self, root_dir, cache_dir="/content/cache/focus", target_size=(1440, 1920)):
        self.root_dir = Path(root_dir)
        self.cache_dir = Path(cache_dir)
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        self.target_size = target_size

        # Find all focus_stacked.tif files
        self.samples = []
        for p in self.root_dir.rglob("*"):
            if p.is_file() and p.suffix.lower() == ".tif" and p.name.lower().endswith("focus_stacked.tif"):
                self.samples.append(p)

        self.samples = sorted(self.samples)
        print(f"  Found {len(self.samples)} focus-stack samples")

    def parallel_precache(self, max_workers=8):
        """Precache all data in parallel"""
        print(f"  Precaching {len(self.samples)} focus-stacks with {max_workers} workers...")

        import re
        tasks = []
        for file_path in self.samples:
            match = re.search(r'(W\d{3})', str(file_path))
            if match:
                well_id = match.group(1)
                cache_path = self.cache_dir / f"{well_id}.npy"
                tasks.append((well_id, file_path, cache_path))

        cached_count = 0
        loaded_count = 0

        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            futures = {
                executor.submit(load_single_focus, w_id, fp, cp, self.target_size): w_id
                for w_id, fp, cp in tasks
            }

            with tqdm(total=len(tasks), desc="  Focus") as pbar:
                for future in as_completed(futures):
                    well_id, status = future.result()
                    if status == "cached":
                        cached_count += 1
                    else:
                        loaded_count += 1
                    pbar.update(1)

        print(f"  ✓ Complete: {cached_count} already cached, {loaded_count} newly loaded")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        import re
        file_path = self.samples[idx]
        match = re.search(r'(W\d{3})', str(file_path))
        if match:
            well_id = match.group(1)
        else:
            raise ValueError(f"Could not extract well ID from: {file_path}")

        cache_path = self.cache_dir / f"{well_id}.npy"

        if not cache_path.exists():
            raise RuntimeError(f"Cache missing for {well_id}. Run parallel_precache() first!")

        img = np.load(cache_path)
        return (img, well_id)

class FastDiskCachedHybridDataset(Dataset):
    """Hybrid results dataset with parallel disk caching"""
    def __init__(self, root_dir, w_count, cache_dir="/content/cache/hybrid"):
        self.root_dir = Path(root_dir)
        self.cache_dir = Path(cache_dir)
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        self.w_count = w_count

        # Find hybrid_results_W### folders
        self.samples = []
        for i in range(1, self.w_count + 1):
            w_id = f"W{i:03d}"
            subfolder = f"hybrid_results_{w_id}"
            w_dir = self.root_dir / subfolder

            if not w_dir.exists():
                continue

            tif_paths = sorted([
                p for p in w_dir.iterdir()
                if p.is_file() and p.suffix.lower() == ".tif"
            ])

            if len(tif_paths) > 0:
                self.samples.append((w_id, tif_paths[0]))

        print(f"  Found {len(self.samples)} hybrid samples")

    def parallel_precache(self, max_workers=8):
        """Precache all data in parallel"""
        print(f"  Precaching {len(self.samples)} hybrid images with {max_workers} workers...")

        tasks = []
        for well_id, tif_path in self.samples:
            cache_path = self.cache_dir / f"{well_id}.npy"
            tasks.append((well_id, tif_path, cache_path))

        cached_count = 0
        loaded_count = 0

        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            futures = {
                executor.submit(load_single_hybrid, w_id, tp, cp): w_id
                for w_id, tp, cp in tasks
            }

            with tqdm(total=len(tasks), desc="  Hybrid") as pbar:
                for future in as_completed(futures):
                    well_id, status = future.result()
                    if status == "cached":
                        cached_count += 1
                    else:
                        loaded_count += 1
                    pbar.update(1)

        print(f"  ✓ Complete: {cached_count} already cached, {loaded_count} newly loaded")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        well_id, _ = self.samples[idx]
        cache_path = self.cache_dir / f"{well_id}.npy"

        if not cache_path.exists():
            raise RuntimeError(f"Cache missing for {well_id}. Run parallel_precache() first!")

        img = np.load(cache_path)
        return (img, well_id)

# ============================================================================
# LABEL LOADING WITH CACHING
# ============================================================================

@lru_cache(maxsize=500)
def load_txt_cached(txt_path):
    """Load and cache bounding box labels"""
    with open(txt_path, 'r') as f:
        lines = [line.strip() for line in f if line.strip()]

    bboxes = []
    for line in lines:
        coords = [float(x) for x in line.split(',')]
        bboxes.append(coords)

    return torch.tensor(bboxes, dtype=torch.float32) if bboxes else torch.zeros((0, 4))

# ============================================================================
# JOINED DATASET
# ============================================================================

class JoinedDataset(Dataset):
    """Combines z-stack, focus, and hybrid images with labels"""
    def __init__(self, zstack_ds, focus_ds, hybrid_ds, labels_dir, kpa):
        self.zstack_ds = zstack_ds
        self.focus_ds = focus_ds
        self.hybrid_ds = hybrid_ds
        self.labels_dir = Path(labels_dir)
        self.kpa = float(kpa)

        assert len(zstack_ds) == len(focus_ds) == len(hybrid_ds), \
            "All component datasets must have the same length"

    def __len__(self):
        return len(self.focus_ds)

    def __getitem__(self, idx):
        z_stack, z_well_id = self.zstack_ds[idx]
        focus_img, f_well_id = self.focus_ds[idx]
        hybrid_img, h_well_id = self.hybrid_ds[idx]

        assert z_well_id == f_well_id == h_well_id, \
            f"Well ID mismatch: {z_well_id}, {f_well_id}, {h_well_id}"

        well_id = z_well_id

        label_path = str(self.labels_dir / f"{well_id}.txt")
        bboxes = load_txt_cached(label_path)

        kpa_tensor = torch.tensor([self.kpa], dtype=torch.float32)

        return {
            'z_stack': z_stack,
            'focus': focus_img,
            'hybrid': hybrid_img,
            'bboxes': bboxes,
            'kpa': kpa_tensor,
            'well_id': well_id
        }

# ============================================================================
# CUSTOM COLLATE FUNCTION
# ============================================================================

def custom_collate_fn(batch):
    """Custom collate to handle variable-length bboxes"""
    z_stacks = torch.stack([torch.from_numpy(item['z_stack']).float() for item in batch])
    focus_imgs = torch.stack([torch.from_numpy(item['focus']).float() for item in batch])
    hybrid_imgs = torch.stack([torch.from_numpy(item['hybrid']).float() for item in batch])
    kpas = torch.stack([item['kpa'] for item in batch])

    bboxes = [item['bboxes'] for item in batch]
    well_ids = [item['well_id'] for item in batch]

    return {
        'z_stack': z_stacks,
        'focus': focus_imgs,
        'hybrid': hybrid_imgs,
        'bboxes': bboxes,
        'kpa': kpas,
        'well_ids': well_ids
    }

# ============================================================================
# MAIN DATALOADER CREATION FUNCTION
# ============================================================================

def create_fast_dataloader(
    zstack_root_900kpa,
    zstack_root_5kpa,
    focus_root_900kpa,
    focus_root_5kpa,
    hybrid_root_900kpa,
    hybrid_root_5kpa,
    labels_900kpa,
    labels_5kpa,
    cache_base_dir="/content/cache",
    batch_size=4,
    num_workers=0,
    shuffle=True,
    max_workers=16,  # Parallel loading threads
    w_count=10
):
    """
    Create fast dataloader with parallel caching

    Args:
        max_workers: Number of parallel threads for caching (default: 16)
                     Higher = faster, but don't go crazy (16-32 is good)
    """

    print("\n" + "=" * 70)
    print("  CREATING FAST PARALLEL-CACHED DATALOADER")
    print("=" * 70 + "\n")

    # Create datasets
    print("Creating 900kPa datasets...")
    zstack_900 = FastDiskCachedZStackDataset(
        zstack_root_900kpa,
        w_count=w_count,
        cache_dir=f"{cache_base_dir}/zstack_900"
    )
    focus_900 = FastDiskCachedFocusStackDataset(
        focus_root_900kpa,
        cache_dir=f"{cache_base_dir}/focus_900",
        target_size=(1440, 1920)
    )
    hybrid_900 = FastDiskCachedHybridDataset(
        hybrid_root_900kpa,
        w_count=w_count,
        cache_dir=f"{cache_base_dir}/hybrid_900"
    )

    print("\nCreating 5kPa datasets...")
    zstack_5 = FastDiskCachedZStackDataset(
        zstack_root_5kpa,
        w_count=w_count,
        cache_dir=f"{cache_base_dir}/zstack_5"
    )
    focus_5 = FastDiskCachedFocusStackDataset(
        focus_root_5kpa,
        cache_dir=f"{cache_base_dir}/focus_5",
        target_size=(1440, 1920)
    )
    hybrid_5 = FastDiskCachedHybridDataset(
        hybrid_root_5kpa,
        w_count=w_count,
        cache_dir=f"{cache_base_dir}/hybrid_5"
    )

    # Parallel precache all data
    print("\n" + "=" * 70)
    print("  PRECACHING ALL DATA IN PARALLEL")
    print(f"  Using {max_workers} parallel workers")
    print("=" * 70 + "\n")

    total_start = time.time()

    print("900kPa datasets:")
    zstack_900.parallel_precache(max_workers=max_workers)
    focus_900.parallel_precache(max_workers=max_workers)
    hybrid_900.parallel_precache(max_workers=max_workers)

    print("\n5kPa datasets:")
    zstack_5.parallel_precache(max_workers=max_workers)
    focus_5.parallel_precache(max_workers=max_workers)
    hybrid_5.parallel_precache(max_workers=max_workers)

    total_time = time.time() - total_start

    print("\n" + "=" * 70)
    print(f"  ALL DATA CACHED in {total_time/60:.1f} minutes!")
    print("=" * 70 + "\n")

    # Create joined datasets
    print("Joining datasets with labels...")
    dataset_900 = JoinedDataset(zstack_900, focus_900, hybrid_900, labels_900kpa, kpa=900)
    dataset_5 = JoinedDataset(zstack_5, focus_5, hybrid_5, labels_5kpa, kpa=5)

    full_dataset = ConcatDataset([dataset_900, dataset_5])
    print(f"Total samples in dataset: {len(full_dataset)}")

    # Create dataloader
    print(f"\nCreating DataLoader (batch_size={batch_size}, num_workers={num_workers})...")
    loader = DataLoader(
        full_dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=num_workers,
        collate_fn=custom_collate_fn,
        pin_memory=True
    )

    print("✓ DataLoader ready!\n")

    return loader, full_dataset

# ============================================================================
# EXAMPLE USAGE
# ============================================================================

if __name__ == "__main__":
    paths_900kpa = {
        'zstack': "/content/drive/MyDrive/Fusion AI/Prof Huang Project/ten_sample_subset/250811_Athchip_noninflam_900kPa",
        'focus': "/content/drive/MyDrive/Fusion AI/Prof Huang Project/ten_sample_subset/20251027_2123__FocusStack_250811_Athchip_noninflam_900kPa",
        'hybrid': "/content/drive/MyDrive/Fusion AI/Prof Huang Project/ten_sample_subset/250811_Athchip_noninflam_900kPa_HybridResults",
        'labels': "/content/drive/MyDrive/Fusion AI/Prof Huang Project/ten_sample_subset/bbox_txt_for_training/900kPa"
    }

    paths_5kpa = {
        'zstack': "/content/drive/MyDrive/Fusion AI/Prof Huang Project/ten_sample_subset/250814_Athchip_non-inflam_5kPa",
        'focus': "/content/drive/MyDrive/Fusion AI/Prof Huang Project/ten_sample_subset/20251027_2215__FocusStack_250814_Athchip_non-inflam_5kPa",
        'hybrid': "/content/drive/MyDrive/Fusion AI/Prof Huang Project/ten_sample_subset/250814_Athchip_non-inflam_5kPa_HybridResults",
        'labels': "/content/drive/MyDrive/Fusion AI/Prof Huang Project/ten_sample_subset/bbox_txt_for_training/5kPa"
    }

    # Create fast dataloader
    loader, dataset = create_fast_dataloader(
        zstack_root_900kpa=paths_900kpa['zstack'],
        zstack_root_5kpa=paths_5kpa['zstack'],
        focus_root_900kpa=paths_900kpa['focus'],
        focus_root_5kpa=paths_5kpa['focus'],
        hybrid_root_900kpa=paths_900kpa['hybrid'],
        hybrid_root_5kpa=paths_5kpa['hybrid'],
        labels_900kpa=paths_900kpa['labels'],
        labels_5kpa=paths_5kpa['labels'],
        cache_base_dir="/content/cache",
        batch_size=2,
        num_workers=0,
        max_workers=16,  # Increase to 24-32 if still slow
        w_count=10
    )

    # Test loading speed
    print("=" * 70)
    print("  TESTING DATALOADER SPEED")
    print("=" * 70 + "\n")

    print("Loading first batch...")
    start = time.time()
    batch = next(iter(loader))
    elapsed = time.time() - start

    print(f"✓ Batch loaded in {elapsed:.2f} seconds")
    print(f"  - Z-stack shape: {batch['z_stack'].shape}")
    print(f"  - Focus shape: {batch['focus'].shape}")
    print(f"  - Hybrid shape: {batch['hybrid'].shape}")
    print(f"  - KPA shape: {batch['kpa'].shape}")

    print("\nLoading second batch...")
    start = time.time()
    batch = next(iter(loader))
    elapsed = time.time() - start
    print(f"✓ Second batch loaded in {elapsed:.2f} seconds\n")

