# -*- coding: utf-8 -*-
"""WORKING zstack+focused+hybrid dataloader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iSd0YS0tIU2tpC2n74zX212I6fW0utXs

# Z-stack 900kPa
"""

from google.colab import drive
drive.mount("/content/drive")

from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
from pathlib import Path
import torch

IMG_EXTS = {".tif"}

ROOT = Path("/content/drive/MyDrive/Fusion AI/Prof Huang Project/250918_Deepmind_CV_Collaboration/250811_Athchip_noninflam_900kPa")

LABEL_DIR = Path(
    "/content/drive/MyDrive/Fusion AI/Prof Huang Project/250918_Deepmind_CV_Collaboration/bbox_txt_for_training/900kPa"
)

class ZStackWithLabelDataset(Dataset):
    """
    One sample per W-folder:
      x: 140 tif images from ROOT/Wxxx/P00001/*.tif  -> returned as tensor [Z, C, H, W]
      y: label text from LABEL_DIR/Wxxx.txt
    """
    def __init__(self, root_dir, label_dir, transform=None, w_prefix="W", w_count=222, p_folder="P00001"):
        self.root_dir = Path(root_dir)
        self.label_dir = Path(label_dir)
        self.transform = transform

        self.samples = []  # list of dicts: {"w_id": "W001", "img_paths": [...], "label_path": Path(...)}

        for i in range(1, w_count + 1):
            w_id = f"{w_prefix}{i:03d}"  # W001..W222

            p_dir = self.root_dir / w_id / p_folder
            label_path = self.label_dir / f"{w_id}.txt"

            if not p_dir.exists():
                print(f"[WARN] Missing image folder: {p_dir}")
                continue

            img_paths = sorted([
                p for p in p_dir.iterdir()
                if p.is_file() and p.suffix.lower() in IMG_EXTS
            ])

            if len(img_paths) == 0:
                print(f"[WARN] No .tif files found in: {p_dir}")
                continue

            if not label_path.exists():
                print(f"[WARN] Missing label file: {label_path}")
                continue

            self.samples.append({
                "w_id": w_id,
                "img_paths": img_paths,
                "label_path": label_path
            })

        if len(self.samples) == 0:
            raise ValueError("No valid (z-stack, label) pairs found. Check ROOT and LABEL_DIR.")

        print(f"\nTotal samples (W folders) loaded: {len(self.samples)}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        sample = self.samples[idx]
        w_id = sample["w_id"]
        img_paths = sample["img_paths"]
        label_path = sample["label_path"]

        # Load stack: list of [C,H,W] -> tensor [Z,C,H,W]
        slices = []
        for p in img_paths:
            with Image.open(p) as im:
                im = im.convert("RGB")
            if self.transform:
                im = self.transform(im)  # [C,H,W]
            else:
                im = transforms.ToTensor()(im)
            slices.append(im)

        stack = torch.stack(slices, dim=0)  # [Z, C, H, W]

        # Read label text (keep as raw text for now; parse later if needed)
        label_text = label_path.read_text()

        return stack, label_text, w_id


tfm = transforms.Compose([
    transforms.PILToTensor(),   # uint8 [C,H,W], not float32
])

z_stack_900kpa = ZStackWithLabelDataset(
    root_dir=ROOT,
    label_dir=LABEL_DIR,
    transform=tfm,
    w_count=222,
    p_folder="P00001"
)

loader_z_stack_900kpa = DataLoader(
    z_stack_900kpa,
    batch_size=1,
    shuffle=True,
    num_workers=0,      # <-- key
    pin_memory=False    # <-- key (esp since you're on CPU right now)
)

stack, label_text, w_id = next(iter(loader_z_stack_900kpa))
print("W id:", w_id[0])
print("Stack shape:", stack.shape)  # [B, Z, C, H, W]
print("Label preview:", label_text[0][:200])

"""# Z-stack 5kPa"""

ROOT = Path("/content/drive/MyDrive/Fusion AI/Prof Huang Project/250918_Deepmind_CV_Collaboration/250814_Athchip_non-inflam_5kPa")

LABEL_DIR = Path(
    "/content/drive/MyDrive/Fusion AI/Prof Huang Project/250918_Deepmind_CV_Collaboration/bbox_txt_for_training/5kPa"
)

z_stack_5kpa = ZStackWithLabelDataset(
    root_dir=ROOT,
    label_dir=LABEL_DIR,
    transform=tfm,
    w_count=222,
    p_folder="P00001"
)

loader_z_stack_5kpa = DataLoader(
    z_stack_5kpa,
    batch_size=1,
    shuffle=True,
    num_workers=0,      # <-- key
    pin_memory=False    # <-- key (esp since you're on CPU right now)
)

stack, label_text, w_id = next(iter(loader_z_stack_5kpa))
print("W id:", w_id[0])
print("Stack shape:", stack.shape)  # [B, Z, C, H, W]
print("Label preview:", label_text[0][:200])

"""# Focused stack 900kpa"""

from google.colab import drive
drive.mount("/content/drive")

from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
from pathlib import Path

IMG_EXTS = {".tif"}
FOCUS_SUFFIX = "focus_stacked.tif"

ROOT = Path("/content/drive/MyDrive/Fusion AI/Prof Huang Project/250918_Deepmind_CV_Collaboration/20251027_2123__FocusStack_250811_Athchip_noninflam_900kPa/")

class DriveImageDataset(Dataset):
    def __init__(self, root_dir, transform=None, recursive=True):
        self.root_dir = Path(root_dir)
        self.transform = transform

        # Choose how to iterate:
        # - recursive=True  -> searches all subfolders too
        # - recursive=False -> only looks at files directly inside ROOT
        iterator = self.root_dir.rglob("*") if recursive else self.root_dir.iterdir()

        self.paths = sorted([
            p for p in iterator
            if p.is_file()
            and p.suffix.lower() in IMG_EXTS
            and p.name.lower().endswith(FOCUS_SUFFIX)
        ])

        if len(self.paths) == 0:
            where = "recursively under" if recursive else "directly in"
            raise ValueError(f"No *{FOCUS_SUFFIX} files found {where} {self.root_dir}")

        print(f"Total focus-stacked tif files loaded: {len(self.paths)}")

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, idx):
        path = self.paths[idx]
        with Image.open(path) as im:
            image = im.convert("RGB")
        if self.transform:
            image = self.transform(image)
        return image, str(path)

tfm = transforms.Compose([
    transforms.Resize((1440, 1920)),
    transforms.ToTensor(),
])


# Set recursive=True to find focus_stacked.tif anywhere under ROOT
focus_stacked_900kpa = DriveImageDataset(root_dir=ROOT, transform=tfm, recursive=True)

"""# Focused stack 5kpa"""

from google.colab import drive
drive.mount("/content/drive")

from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
from pathlib import Path

IMG_EXTS = {".tif"}
FOCUS_SUFFIX = "focus_stacked.tif"

ROOT = Path("/content/drive/MyDrive/Fusion AI/Prof Huang Project/250918_Deepmind_CV_Collaboration/20251027_2215__FocusStack_250814_Athchip_non-inflam_5kPa/")

class DriveImageDataset(Dataset):
    def __init__(self, root_dir, transform=None, recursive=True):
        self.root_dir = Path(root_dir)
        self.transform = transform

        # Choose how to iterate:
        # - recursive=True  -> searches all subfolders too
        # - recursive=False -> only looks at files directly inside ROOT
        iterator = self.root_dir.rglob("*") if recursive else self.root_dir.iterdir()

        self.paths = sorted([
            p for p in iterator
            if p.is_file()
            and p.suffix.lower() in IMG_EXTS
            and p.name.lower().endswith(FOCUS_SUFFIX)
        ])

        if len(self.paths) == 0:
            where = "recursively under" if recursive else "directly in"
            raise ValueError(f"No *{FOCUS_SUFFIX} files found {where} {self.root_dir}")

        print(f"Total focus-stacked tif files loaded: {len(self.paths)}")

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, idx):
        path = self.paths[idx]
        with Image.open(path) as im:
            image = im.convert("RGB")
        if self.transform:
            image = self.transform(image)
        return image, str(path)

tfm = transforms.Compose([
    transforms.Resize((1440, 1920)),
    transforms.ToTensor(),
])


# Set recursive=True to find focus_stacked.tif anywhere under ROOT
focus_stacked_5kpa = DriveImageDataset(root_dir=ROOT, transform=tfm, recursive=True)

"""# Hybrid results 900kpa"""

from google.colab import drive
drive.mount("/content/drive")

from torch.utils.data import Dataset
from torchvision import transforms
from PIL import Image
from pathlib import Path

IMG_EXTS = {".tif"}

ROOT = Path("/content/drive/MyDrive/Fusion AI/Prof Huang Project/250918_Deepmind_CV_Collaboration/250811_Athchip_noninflam_900kPa_HybridResults")

class DriveImageDataset(Dataset):
    """
    Expects folder structure:
      ROOT/hybrid_results_W001/*.tif
      ROOT/hybrid_results_W002/*.tif
      ...
      ROOT/hybrid_results_W222/*.tif
    """
    def __init__(self, root_dir, transform=None, w_count=222, folder_prefix="hybrid_results_W"):
        self.root_dir = Path(root_dir)
        self.transform = transform
        self.paths = []

        for i in range(1, w_count + 1):
            subfolder = f"{folder_prefix}{i:03d}"   # hybrid_results_W001, ...
            w_dir = self.root_dir / subfolder

            if not w_dir.exists():
                print(f"[WARN] Missing folder: {w_dir}")
                continue

            tif_paths = sorted([
                p for p in w_dir.iterdir()
                if p.is_file() and p.suffix.lower() in IMG_EXTS
            ])

            if len(tif_paths) == 0:
                print(f"[WARN] No .tif files found in: {w_dir}")
                continue

            self.paths.extend(tif_paths)
            # print(f"[OK] {subfolder}: {len(tif_paths)} tif files")

        if len(self.paths) == 0:
            raise ValueError(f"No .tif files found under expected structure in {self.root_dir}")

        print(f"\nTotal tif files loaded: {len(self.paths)}")

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, idx):
        path = self.paths[idx]
        with Image.open(path) as im:
            image = im.convert("RGB")
        if self.transform:
            image = self.transform(image)
        return image, str(path)

tfm = transforms.Compose([
    transforms.ToTensor(),
])

hybrid_900kpa = DriveImageDataset(root_dir=ROOT, transform=tfm, w_count=222)

"""# Hybrid results 5kpa"""

from google.colab import drive
drive.mount("/content/drive")

from torch.utils.data import Dataset
from torchvision import transforms
from PIL import Image
from pathlib import Path

IMG_EXTS = {".tif"}

ROOT = Path("/content/drive/MyDrive/Fusion AI/Prof Huang Project/250918_Deepmind_CV_Collaboration/250814_Athchip_non-inflam_5kPa_HybridResults")

class DriveImageDataset(Dataset):
    """
    Expects folder structure:
      ROOT/hybrid_results_W001/*.tif
      ROOT/hybrid_results_W002/*.tif
      ...
      ROOT/hybrid_results_W222/*.tif
    """
    def __init__(self, root_dir, transform=None, w_count=222, folder_prefix="hybrid_results_W"):
        self.root_dir = Path(root_dir)
        self.transform = transform
        self.paths = []

        for i in range(1, w_count + 1):
            subfolder = f"{folder_prefix}{i:03d}"   # hybrid_results_W001, ...
            w_dir = self.root_dir / subfolder

            if not w_dir.exists():
                print(f"[WARN] Missing folder: {w_dir}")
                continue

            tif_paths = sorted([
                p for p in w_dir.iterdir()
                if p.is_file() and p.suffix.lower() in IMG_EXTS
            ])

            if len(tif_paths) == 0:
                print(f"[WARN] No .tif files found in: {w_dir}")
                continue

            self.paths.extend(tif_paths)
            # print(f"[OK] {subfolder}: {len(tif_paths)} tif files")

        if len(self.paths) == 0:
            raise ValueError(f"No .tif files found under expected structure in {self.root_dir}")

        print(f"\nTotal tif files loaded: {len(self.paths)}")

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, idx):
        path = self.paths[idx]
        with Image.open(path) as im:
            image = im.convert("RGB")
        if self.transform:
            image = self.transform(image)
        return image, str(path)

tfm = transforms.Compose([
    transforms.ToTensor(),
])

hybrid_5kpa = DriveImageDataset(root_dir=ROOT, transform=tfm, w_count=222)

"""# Helper functions"""

import re
from pathlib import Path
import torch
from torch.utils.data import Dataset, DataLoader

W_RE = re.compile(r"(W\d{3})")

def get_well_id_from_anything(x):
    """
    Try to extract W### from a path/string or dict.
    Adjust based on what your dataset returns.
    """
    if isinstance(x, dict):
        # common keys that might contain the filepath or id
        for k in ["path", "filepath", "file", "fname", "id", "name"]:
            if k in x and x[k] is not None:
                m = W_RE.search(str(x[k]))
                if m: return m.group(1)
    m = W_RE.search(str(x))
    if not m:
        raise ValueError(f"Could not find W### in: {x}")
    return m.group(1)

def load_txt(txt_path: Path):
    rows = []
    with open(txt_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            # Expect: "x1,y1,x2,y2" (possibly with spaces)
            parts = [p.strip() for p in line.split(",")]
            if len(parts) != 4:
                raise ValueError(f"Expected 4 comma-separated numbers in {txt_path.name}, got: {line}")
            rows.append([float(p) for p in parts])
    # shape [N, 4]; if no boxes, return [0,4] tensor
    return torch.tensor(rows, dtype=torch.float32) if rows else torch.zeros((0, 4), dtype=torch.float32)


class JoinTwoDatasetsWithTxt(Dataset):
    def __init__(self, zstack_ds, focus_ds, hybrid_ds, labels_dir, kpa, id_getter=None):
        self.zstack_ds = zstack_ds
        self.focus_ds = focus_ds
        self.hybrid_ds = hybrid_ds
        self.labels_dir = Path(labels_dir)
        self.id_getter = id_getter or get_well_id_from_anything
        self.kpa = float(kpa)

    def __len__(self):
        return len(self.focus_ds)

    def __getitem__(self, idx):
        a = self.zstack_ds[idx]
        b = self.focus_ds[idx]
        c = self.hybrid_ds[idx]

        wid = self.id_getter(b[1])
        y_path = self.labels_dir / f"{wid}.txt"
        y = load_txt(y_path)

        # return kpa as a real model input feature (tensor)
        kpa = torch.tensor([self.kpa], dtype=torch.float32)  # shape [1]
        return a, b, c, y, kpa


def collate_join(batch):
    a_list, b_list, c_list, y_list, kpa_list = zip(*batch)

    a_imgs  = torch.stack([a[0] for a in a_list])
    a_paths = [a[1] for a in a_list]

    b_imgs  = torch.stack([b[0] for b in b_list])
    b_paths = [b[1] for b in b_list]

    c_imgs  = torch.stack([c[0] for c in c_list])
    c_paths = [c[1] for c in c_list]

    y = list(y_list)                 # list of [Ni,4]
    kpa = torch.stack(kpa_list)      # [B, 1]

    return {
        "zstack": a_imgs,
        "focus": b_imgs,
        "hybrid": c_imgs,
        "y": y,
        "kpa": kpa,
        "zstack_paths": a_paths,
        "focus_paths": b_paths,
        "hybrid_paths": c_paths,
    }


joined_900 = JoinTwoDatasetsWithTxt(
    z_stack_900kpa, focus_stacked_900kpa, hybrid_900kpa,
    "/content/drive/MyDrive/Fusion AI/Prof Huang Project/250918_Deepmind_CV_Collaboration/bbox_txt_for_training/900kPa",
    kpa=900
)

joined_5 = JoinTwoDatasetsWithTxt(
    z_stack_5kpa, focus_stacked_5kpa, hybrid_5kpa,
    "/content/drive/MyDrive/Fusion AI/Prof Huang Project/250918_Deepmind_CV_Collaboration/bbox_txt_for_training/5kPa",
    kpa=5
)

from torch.utils.data import ConcatDataset

full_zstack_focused_and_hybrid = ConcatDataset([joined_900, joined_5])
loader = DataLoader(full_zstack_focused_and_hybrid, batch_size=4, shuffle=True, collate_fn=collate_join)

"""# Testing it out with print statements (it worked)"""

import random


# ---- Random sample from the *dataset* (not the loader) ----
print(len(full_zstack_focused_and_hybrid))
idx = random.randrange(len(full_zstack_focused_and_hybrid))
a, b, c, y, kpa = full_zstack_focused_and_hybrid[idx]

# a = (stack, label_text, w_id) from ZStackWithLabelDataset
# b = (focus_img, focus_path)
# c = (hybrid_img, hybrid_path)
# y = [N,4] tensor of boxes
# kpa = [1] tensor

print("=== RANDOM SAMPLE (dataset) ===")
print("idx:", idx)

stack, label_text, w_id = a
focus_img, focus_path = b
hybrid_img, hybrid_path = c

print("w_id (from zstack):", w_id)
print("focus_path:", focus_path)
print("hybrid_path:", hybrid_path)

print("zstack stack shape [Z,C,H,W]:", tuple(stack.shape), "dtype:", stack.dtype)
print("focus_img shape [C,H,W]:", tuple(focus_img.shape), "dtype:", focus_img.dtype)
print("hybrid_img shape [C,H,W]:", tuple(hybrid_img.shape), "dtype:", hybrid_img.dtype)

print("kpa tensor:", kpa, "shape:", tuple(kpa.shape), "dtype:", kpa.dtype)

print("y (bboxes) shape:", tuple(y.shape), "dtype:", y.dtype)
if y.numel() > 0:
    print("first bbox [x1,y1,x2,y2]:", y[0].tolist())
else:
    print("no bboxes in this label file.")

print("raw label_text preview (first 200 chars):")
print(label_text[:200])
print()

# ---- One batch from the *loader* ----
batch = next(iter(loader))

print("=== ONE BATCH (loader) ===")
print("batch keys:", list(batch.keys()))

print("zstack:", tuple(batch["zstack"].shape), batch["zstack"].dtype)   # [B,Z,C,H,W]
print("focus:",  tuple(batch["focus"].shape),  batch["focus"].dtype)    # [B,C,H,W]
print("hybrid:", tuple(batch["hybrid"].shape), batch["hybrid"].dtype)   # [B,C,H,W]
print("kpa:",    tuple(batch["kpa"].shape),    batch["kpa"].dtype)      # [B,1]

# y is a list of length B, each element is [Ni,4]
print("y: list length =", len(batch["y"]))
for i, yi in enumerate(batch["y"]):
    print(f"  y[{i}] shape:", tuple(yi.shape), "num_boxes:", yi.shape[0])

print("example paths:")
print("  focus_paths[0]:", batch["focus_paths"][0])
print("  zstack_paths[0]:", batch["zstack_paths"][0])
print("  hybrid_paths[0]:", batch["hybrid_paths"][0])